// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: mcenter/apps/policy/pb/rpc.proto

package policy

import (
	user "github.com/kade-chen/mcenter/apps/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// var permission_message success = "permission success"
type Permission_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// string message = 1;
	// @gotags: bson:"message" json:"message"
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message" bson:"message"`
}

func (x *Permission_Message) Reset() {
	*x = Permission_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mcenter_apps_policy_pb_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Permission_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission_Message) ProtoMessage() {}

func (x *Permission_Message) ProtoReflect() protoreflect.Message {
	mi := &file_mcenter_apps_policy_pb_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission_Message.ProtoReflect.Descriptor instead.
func (*Permission_Message) Descriptor() ([]byte, []int) {
	return file_mcenter_apps_policy_pb_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *Permission_Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type User_Permission_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @tags: bson:"user" json:"user"
	User []*user.User `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	// @tags: bson:"roles_admin" json:"roles_admin"
	Roles_Admin string `protobuf:"bytes,2,opt,name=Roles_Admin,json=RolesAdmin,proto3" json:"Roles_Admin,omitempty"`
	// @tags: bson:"permission_name" json:"permission_name"
	Permission_Name string `protobuf:"bytes,3,opt,name=Permission_Name,json=PermissionName,proto3" json:"Permission_Name,omitempty"`
}

func (x *User_Permission_Request) Reset() {
	*x = User_Permission_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mcenter_apps_policy_pb_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User_Permission_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Permission_Request) ProtoMessage() {}

func (x *User_Permission_Request) ProtoReflect() protoreflect.Message {
	mi := &file_mcenter_apps_policy_pb_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Permission_Request.ProtoReflect.Descriptor instead.
func (*User_Permission_Request) Descriptor() ([]byte, []int) {
	return file_mcenter_apps_policy_pb_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *User_Permission_Request) GetUser() []*user.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *User_Permission_Request) GetRoles_Admin() string {
	if x != nil {
		return x.Roles_Admin
	}
	return ""
}

func (x *User_Permission_Request) GetPermission_Name() string {
	if x != nil {
		return x.Permission_Name
	}
	return ""
}

var File_mcenter_apps_policy_pb_rpc_proto protoreflect.FileDescriptor

var file_mcenter_apps_policy_pb_rpc_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x15, 0x67, 0x6f, 0x6b, 0x61, 0x64, 0x65, 0x2e, 0x6d, 0x63, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x1a, 0x1f, 0x6d, 0x63, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x12, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x17, 0x55,
	0x73, 0x65, 0x72, 0x5f, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6b, 0x61, 0x64, 0x65, 0x2e, 0x6d, 0x63,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x5f, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x32,
	0x74, 0x0a, 0x03, 0x52, 0x50, 0x43, 0x12, 0x6d, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x5f,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x2e, 0x67, 0x6f, 0x6b,
	0x61, 0x64, 0x65, 0x2e, 0x6d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x67, 0x6f, 0x6b,
	0x61, 0x64, 0x65, 0x2e, 0x6d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x65, 0x65, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x6b, 0x61, 0x64, 0x65, 0x2f, 0x6d, 0x63, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mcenter_apps_policy_pb_rpc_proto_rawDescOnce sync.Once
	file_mcenter_apps_policy_pb_rpc_proto_rawDescData = file_mcenter_apps_policy_pb_rpc_proto_rawDesc
)

func file_mcenter_apps_policy_pb_rpc_proto_rawDescGZIP() []byte {
	file_mcenter_apps_policy_pb_rpc_proto_rawDescOnce.Do(func() {
		file_mcenter_apps_policy_pb_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_mcenter_apps_policy_pb_rpc_proto_rawDescData)
	})
	return file_mcenter_apps_policy_pb_rpc_proto_rawDescData
}

var file_mcenter_apps_policy_pb_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mcenter_apps_policy_pb_rpc_proto_goTypes = []interface{}{
	(*Permission_Message)(nil),      // 0: gokade.mcenter.policy.Permission_Message
	(*User_Permission_Request)(nil), // 1: gokade.mcenter.policy.User_Permission_Request
	(*user.User)(nil),               // 2: gokade.mcenter.user.User
}
var file_mcenter_apps_policy_pb_rpc_proto_depIdxs = []int32{
	2, // 0: gokade.mcenter.policy.User_Permission_Request.user:type_name -> gokade.mcenter.user.User
	1, // 1: gokade.mcenter.policy.RPC.Check_Permission:input_type -> gokade.mcenter.policy.User_Permission_Request
	0, // 2: gokade.mcenter.policy.RPC.Check_Permission:output_type -> gokade.mcenter.policy.Permission_Message
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mcenter_apps_policy_pb_rpc_proto_init() }
func file_mcenter_apps_policy_pb_rpc_proto_init() {
	if File_mcenter_apps_policy_pb_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mcenter_apps_policy_pb_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Permission_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mcenter_apps_policy_pb_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User_Permission_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mcenter_apps_policy_pb_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcenter_apps_policy_pb_rpc_proto_goTypes,
		DependencyIndexes: file_mcenter_apps_policy_pb_rpc_proto_depIdxs,
		MessageInfos:      file_mcenter_apps_policy_pb_rpc_proto_msgTypes,
	}.Build()
	File_mcenter_apps_policy_pb_rpc_proto = out.File
	file_mcenter_apps_policy_pb_rpc_proto_rawDesc = nil
	file_mcenter_apps_policy_pb_rpc_proto_goTypes = nil
	file_mcenter_apps_policy_pb_rpc_proto_depIdxs = nil
}
